app_id: "YOUR_APP_ID_HERE"
app_secret: "Y9603eaaa-6101-4f77-9b4d-094fbde019fa"
redirect: "http://localhost:8000/callback"
scopes:
  - user.read
  - mailboxsettings.read
  - calendars.readwrite
authority: "https://login.microsoftonline.com/common"